### ISSUE TITLE
Terminal does not work in Firefox.

### ISSUE THREAD

**Issue by ktos** [Ulterius/client#10]
When I am trying to open Terminal in Client I get only "Please Login to continue (ulterius-auth)" and Windows command line information, but nothing more - I cannot type in any command.

In server logs there are:
```
Connection from 192.168.8.143:49819
UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.AesHandshakeRequest
UlteriusServer.TerminalServer.Messaging.TerminalControl.Requests.CreateTerminalRequest
```

Process Explorer confirms that Ulterius spawned conhost.exe and cmd.exe. I am using Firefox 48, this may be the issue?

**Comment by Codeusa** [comment]
@ktos see if you can reproduce the issue in chrome

**Comment by Codeusa** [comment]
Right, you have to authorize the instance of the terminal (better safe than sorry) so you type "ulterius-auth" which prompts for the password

**Comment by ktos** [comment]
Yeah, it works. I had no idea it works that way, could be more explained what is ulterius-auth :-)

So the bug is: terminal does not work under Firefox.
