### ISSUE TITLE
CPU and VIDEO CARDS TEMPERATURE not working

### ISSUE THREAD

**Issue by Maksim112** [Ulterius/client#26]

**Comment by Codeusa** [comment]
Going to need a lot more specific details, what kind of CPU/Card do you have? What operating system are you running?

**Comment by Stegorix** [comment]
I can confirm this Error. I attached a screenshot with all necessary information (hopefully):
![screen](https://cloud.githubusercontent.com/assets/21155544/20119822/504b7a4c-a60a-11e6-8c57-275f2fe1abc7.png)

And the logfile:
![log](https://cloud.githubusercontent.com/assets/21155544/20120111/9f29cf0a-a60b-11e6-9bed-4dd1a48ac271.PNG)

**Comment by Codeusa** [comment]
Thanks @Stegorix 

I've found a solution and will include it in the next update.

**Comment by Codeusa** [comment]
Fixed
