### ISSUE TITLE
blank screen and erros

### ISSUE THREAD

**Issue by vicochips** [Ulterius/client#28]
Hello, 

Is anyone have the solution for this error and blank screen on windows 10?

![2016-11-29_17-41-33](https://cloud.githubusercontent.com/assets/14276142/20719113/43e4b7d0-b65b-11e6-9ce9-d5723f1f74bc.png)

Regards :)

**Comment by Codeusa** [comment]
What version of firefox is this?

**Comment by vicochips** [comment]
Hey :) ,

It is the last version 50.0.1, no it is not working on chrome too.
