### ISSUE TITLE
ulterius "invalid password" on remote access. local works ok.

### ISSUE THREAD

**Issue by rdeleonp** [Ulterius/client#31]
As per $SUBJECT:
- Trying via http://127.0.0.1:22006/, get login screen, input credentials, no problem.
- Trying via http://client.ulterius.io/, get login screen, input credentials, "invalid password".

**Comment by Codeusa** [comment]
Hi @rdeleonp 

Sorry for the issue, seems the sync server failed to sync the new client to the public client. It should be fixed now.

**Comment by rdeleonp** [comment]
Just tested it. Everything's OK. Thanks a lot.
